version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - echo Logging in to Amazon ...
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the code...
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - index.html
    - index2.html
    - appspec.yml
    - scripts/install_dependencies
    - scripts/start_server
    - scripts/stop_server