phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ...
      - cd web
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the code...
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - index.html