version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Logging in to Amazon ...
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the code...
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - index.html
    - index2.html